//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcions
    {
        public Funcions()
        {
            this.RoleFuncions = new HashSet<RoleFuncions>();
        }
    
        public int id { get; set; }
        public int moduloId { get; set; }
        public string descripcionCorta { get; set; }
        public string descripcionLarga { get; set; }
        public string accion { get; set; }
        public string controlador { get; set; }
        public string estatus { get; set; }
        public int usuarioId { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string tipo { get; set; }
    
        public virtual Modulos Modulos { get; set; }
        public virtual ICollection<RoleFuncions> RoleFuncions { get; set; }
    }
}
