//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupos
    {
        public Grupos()
        {
            this.Clientes = new HashSet<Clientes>();
        }
    
        public int Id { get; set; }
        public string claveGrupo { get; set; }
        public string nombre { get; set; }
        public string nombreCorto { get; set; }
        public int Plaza_id { get; set; }
        public string posicion { get; set; }
        public string estatus { get; set; }
    
        public virtual ICollection<Clientes> Clientes { get; set; }
        public virtual Plazas Plazas { get; set; }
    }
}
