//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plazas
    {
        public Plazas()
        {
            this.Acreditados = new HashSet<Acreditados>();
            this.Asegurados = new HashSet<Asegurados>();
            this.Clientes = new HashSet<Clientes>();
            this.Grupos = new HashSet<Grupos>();
            this.Patrones = new HashSet<Patrones>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public string cvecorta { get; set; }
        public string indicador { get; set; }
    
        public virtual ICollection<Acreditados> Acreditados { get; set; }
        public virtual ICollection<Asegurados> Asegurados { get; set; }
        public virtual ICollection<Clientes> Clientes { get; set; }
        public virtual ICollection<Grupos> Grupos { get; set; }
        public virtual ICollection<Patrones> Patrones { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
