//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleModulos
    {
        public int id { get; set; }
        public int roleId { get; set; }
        public int moduloId { get; set; }
        public int usuarioCreacionId { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    
        public virtual Modulos Modulos { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
