//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.RoleFuncions = new HashSet<RoleFuncions>();
            this.RoleModulos = new HashSet<RoleModulos>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string estatus { get; set; }
    
        public virtual ICollection<RoleFuncions> RoleFuncions { get; set; }
        public virtual ICollection<RoleModulos> RoleModulos { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
